version: '3.8'

services:
  # Servicio para la aplicación Streamlit (Frontend)
  streamlit_app:
    build:
      context: . # El contexto de construcción es la raíz del proyecto
      dockerfile: ./app_streamlit/Dockerfile # Ruta al Dockerfile de Streamlit
    ports:
      - "8501:8501" # Mapea el puerto 8501 del contenedor al puerto 8501 de tu máquina
    volumes:
      # Monta el código de tu app en un SUBDIRECTORIO dentro de /app.
      # Esto es CRUCIAL para que las rutas relativas de app.py (../models) funcionen.
      - ./app_streamlit:/app/streamlit_code
      # Monta los modelos y reportes al mismo nivel que el subdirectorio de la app.
      - ./models:/app/models
      - ./reports:/app/reports
    env_file:
      - ./.env # Carga la GROQ_API_KEY y otras variables desde tu archivo .env
    environment:
      FLASK_HOST: flask_backend # <--- ¡CAMBIO CLAVE AQUÍ! Streamlit encontrará Flask por este nombre
    depends_on:
      - flask_backend # Streamlit depende de que Flask esté corriendo
    networks:
      - app_network # Ambas aplicaciones en la misma red

  # Servicio para el backend Flask
  flask_backend:
    build:
      context: . # El contexto de construcción es la raíz del proyecto
      dockerfile: ./backend/Dockerfile # Ruta al Dockerfile de Flask
    ports:
      - "5000:5000" # Mapea el puerto 5000 del contenedor al puerto 5000 de tu máquina
    volumes:
      # Monta el código de tu backend para desarrollo en vivo.
      - ./backend:/app
      # Monta la carpeta de credenciales para que Flask pueda acceder a ella.
      - ./backend/credentials:/app/credentials # <--- ¡CAMBIO CLAVE AQUÍ! Asegura acceso a credenciales
    env_file:
      - ./.env # Carga variables de entorno para Flask (si las necesita)
    networks:
      - app_network # Ambas aplicaciones en la misma red

# Define la red para que los servicios puedan comunicarse entre sí
networks:
  app_network:
    driver: bridge
